services:
  qualtet_local_db:
    image: ghcr.io/yoshinorin/docker-mariadb:v11.4.3
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_USER: root
      MARIADB_PASSWORD: pass
      MARIADB_DATABASE: qualtet
    volumes:
      - ./data/local:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    command: >
        mariadbd --character-set-server=utf8mb4 --general_log=1 --general_log_file=/var/log/mysql/general.log --innodb-ft-min-token-size=2 &&
        mariadb-upgrade
    restart: unless-stopped
