version: '3'
services:
  qualtet_mariadb:
    image: ghcr.io/yoshinorin/docker-mariadb:v10.11.3
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: qualtet
    volumes:
      - ./data:/var/lib/mysql
    hostname: qualtet-mariadb
    networks:
      - qualtet
    container_name: qualtet-mariadb
    expose:
      - "3306"
    ports:
      - "3306:3306"
    # NOTE:
    #        - `--innodb-ft-min-token-size=<n>`: please fill <n> by your search settings.
    command: ["mysqld", "--character-set-server=utf8mb4", "--innodb-ft-min-token-size=2"]
    restart: unless-stopped
  qualtet:
    # build: .
    image: ghcr.io/yoshinorin/docker-qualtet:latest
    # NOTE: these values are examples. Please fill by yourself.
    environment:
      QUALTET_DB_DATASOURCE_URL: jdbc:mariadb://qualtet-mariadb:3306/qualtet?useUnicode=true&characterEncoding=utf8mb4
      QUALTET_DB_USER: root
      QUALTET_DB_PASSWORD: pass
      QUALTET_HTTP_BIND_ADDRESS: 0.0.0.0
      QUALTET_HTTP_PORT: 9001
      QUALTET_JWT_ISS: "http://localhost:9001"
      QUALTET_JWT_AUD: "qualtet_dev_1111"
      JAVA_OPTS: "-Xms512M -Xmx768M -Xss2M -Xlog:gc*=info:file=/usr/opt/qualtet/logs/gc.log -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/opt/qualtet/dumps/heapdump.bin"
    volumes:
      - ./logs:/usr/opt/qualtet/logs
      - ./dumps:/usr/opt/qualtet/dumps
    hostname: qualtet
    networks:
      - qualtet
    container_name: qualtet
    ports:
      - "9001:9001"
    depends_on:
      - qualtet_mariadb
networks:
  qualtet:
