version: '3'
services:
  qualtet_mariadb:
    image: yoshinorin/docker-mariadb:10.6.3
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: qualtet
    volumes:
      - ./data:/var/lib/mysql
    hostname: qualtet-mariadb
    networks:
      - qualtet
    container_name: qualtet-mariadb
    expose:
      - "3306"
    ports:
      - "3306:3306"
    command: ["mysqld", "--character-set-server=utf8mb4"]
    restart: unless-stopped
  qualtet:
    image: ghcr.io/yoshinorin/docker-qualtet:latest
    # NOTE: these values are examples. Please fill by yourself.
    environment:
      QUALTET_DB_DATASOURCE_URL: jdbc:mariadb://qualtet-mariadb:3306/qualtet?useUnicode=true&characterEncoding=utf8mb4
      QUALTET_DB_USER: root
      QUALTET_DB_PASSWORD: pass
      QUALTET_HTTP_BIND_ADDRESS: 0.0.0.0
      QUALTET_HTTP_PORT: 9001
      QUALTET_JWT_ISS: "http://localhost:9001"
      QUALTET_JWT_AUD: "qualtet_dev_1111"
      JAVA_OPTS: "-Xms512M -Xmx768M -Xss2M"
    volumes:
      - ./logs:/usr/opt/qualtet/logs
    hostname: qualtet
    networks:
      - qualtet
    container_name: qualtet
    expose:
      - "9001"
    ports:
      - "9001:9001"
    depends_on:
      - qualtet_mariadb
networks:
  qualtet:
