services:
  qualtet_mariadb:
    image: ghcr.io/yoshinorin/docker-mariadb:v11.4.5
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_USER: root
      MARIADB_PASSWORD: pass
      MARIADB_DATABASE: qualtet
    volumes:
      - ./data:/var/lib/mysql
    hostname: qualtet-mariadb
    networks:
      - qualtet
    container_name: qualtet-mariadb
    expose:
      - "3306"
    ports:
      - "3306:3306"
    # NOTE:
    #        - `--innodb-ft-min-token-size=<n>`: please fill <n> by your search settings.
    command: >
        mariadbd --character-set-server=utf8mb4 --general_log=1 --general_log_file=/var/log/mysql/general.log --innodb-ft-min-token-size=2 &&
        mariadb-upgrade
    restart: unless-stopped
  qualtet:
    # build: .
    image: ghcr.io/yoshinorin/docker-qualtet:latest
    # NOTE: these values are examples. Please fill by yourself.
    environment:
      QUALTET_DB_DATASOURCE_URL: jdbc:mariadb://qualtet-mariadb:3306/qualtet?useUnicode=true&characterEncoding=utf8mb4
      QUALTET_DB_USER: root
      QUALTET_DB_PASSWORD: pass
      QUALTET_HTTP_BIND_ADDRESS: 0.0.0.0
      QUALTET_HTTP_ENDPOINT_SYSTEM_METADATA_ENABLED: true
      QUALTET_HTTP_PORT: 9001
      QUALTET_JWT_ISS: "http://localhost:9001"
      QUALTET_JWT_AUD: "qualtet_dev_1111"
      JAVA_OPTS: "-Xms512M -Xmx768M -Xss2M -Xlog:gc*=info:file=/usr/opt/qualtet/logs/gc.log -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/opt/qualtet/dumps/heapdump.bin"
    volumes:
      - ./logs:/usr/opt/qualtet/logs
      - ./dumps:/usr/opt/qualtet/dumps
    hostname: qualtet
    networks:
      - qualtet
    container_name: qualtet
    ports:
      - "9001:9001"
    depends_on:
      - qualtet_mariadb
networks:
  qualtet:
