name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - 'docker/**'
      - LICENSE
      - README.md

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [17]
        scala: [3.2.2]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-sbt-libs
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier/v1
          key: build-${{ env.cache-name }}-${{ hashFiles('build.sbt') }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Create log file
        working-directory: .
        # Workaround for suddenly happen permission denied
        run: mkdir logs && touch ./logs/test.log

      - name: Run tests
        working-directory: .
        run: cp .env.example .env && sbt clean coverage testWithDb

      - name: Send Coverage Report
        working-directory: .
        run: cp .env.example .env && sbt coverageReport coveralls
        env:
          # NOTE: send coverage report failed caused by `Couldn't find a repository matching this job.`
          # COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}

