name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - 'docker/**.yml'
      - LICENSE
      - README.md

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [21]
        scala: [3.4.0]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Compile
        working-directory: .
        run: sbt compile

      - name: Caching
        uses: coursier/cache-action@v6

      - name: Create log file
        working-directory: .
        # Workaround for suddenly happen permission denied
        run: mkdir logs && touch ./logs/test.log

      - name: Run tests
        working-directory: .
        run: cp .env.example .env && sbt clean coverage testWithDb

      - name: Send Coverage Report
        working-directory: .
        run: cp .env.example .env && sbt coverageReport coveralls
        env:
          # NOTE: send coverage report failed caused by `Couldn't find a repository matching this job.`
          # COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}

