name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17]
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-sbt-libs
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier/v1
          key: build-${{ env.cache-name }}-${{ hashFiles('build.sbt') }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Create log file
        working-directory: .
        # Workaround for suddenly happen permission denied
        run: touch ./logs/test.log

      - name: Run tests
        working-directory: .
        run: source ./scripts/devenv.sh && sbt clean coverage testWithDb

      - name: Send Coverage Report
        working-directory: .
        run: source ./scripts/devenv.sh && sbt coverageReport coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}
