name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [17]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-sbt-libs
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier/v1
          key: build-${{ env.cache-name }}-${{ hashFiles('build.sbt') }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Create log file
        working-directory: .
        # Workaround for suddenly happen permission denied
        run: mkdir logs && touch ./logs/test.log

      - name: Run tests
        working-directory: .
        run: |
            if [[ "$RUNNER_OS" == "Linux" ]]; then
              source ./scripts/devenv.sh && sbt clean coverage testWithDb
            elif [[ "$RUNNER_OS" == "Windows" ]]; then
              source ./scripts/devenv.bat && sbt clean coverage testWithDb
            else
              echo "$RUNNER_OS not supported"
              exit 1
            fi

      - name: Send Coverage Report
        working-directory: .
        run: |
            if [[ "$RUNNER_OS" == "Linux" ]]; then
              source ./scripts/devenv.sh && sbt clean coverage testWithDb
            elif [[ "$RUNNER_OS" == "Windows" ]]; then
              source ./scripts/devenv.bat && sbt clean coverage testWithDb
            else
              echo "$RUNNER_OS not supported"
              exit 1
            fi

        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}
