name: Build Docker image

on:
  push:
    paths:
      - 'docker/Dockerfile'
  pull_request:
    paths:
      - 'docker/Dockerfile'
  workflow_dispatch:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #6.0.1
      -
        name: Build Docker image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc #7.4.0
        with:
          context: .
          file: docker/Dockerfile
          push: false
